---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cluster-api-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace: flux-system
  install:
    createNamespace: true
    disableHooks: true
  interval: 1m0s
  releaseName: capi-operator
  targetNamespace: capi-operator-system

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/cluster-api-operator
